[project]
name = "apple220908"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "manim>=0.19.0",
    "opencv-python>=4.12.0.88",
    "pycairo>=1.20.0",
    "tyro>=0.5.0",
]
